### ISSUE TITLE
goHealthy already exists in business, need change

### ISSUE THREAD

**Issue by lucasvufma** [TecEngineering/goHealthy#1]
With some research in google, I've found some company(s) with the same business name than us, need change !
> 1. https://gohealthy.co.nz/ 2. https://www.linkedin.com/company/go-healthy/?originalSubdomain=pt 3. https://www.healthpost.co.nz/go-healthy/?sort=bestselling

**Comment by MelquiasRibeiro** [comment]
ok, we can call this GoingHealthy or GogoHealthy.

**Comment by lucasvufma** [comment]
its hoove now
